#!/bin/bash

# pain in the arse unicode whitespace
WHITESPACE=$(printf "%b" "\U00A0\U1680\U180E\U2000\U2001\U2002\U2003\U2004\U2005\U2006\U2007\U2008\U2009\U200A\U200B\U202F\U205F\U3000\UFEFF")

# Strip extra readable material and generate one entry per book per line
cat $1\
| sed 's/['"$WHITESPACE"']/ /g
s/\r//g
/^TITLE and AUTHOR[[:space:]]*EBOOK NO./,/^<==End of GUTINDEX.ALL==>/!d
/^TITLE and AUTHOR[[:space:]]*EBOOK NO./d
/^<==End of GUTINDEX.ALL==>/d'\
| sed '#n
/^[^ ]\+.*[[:space:]]\+[0-9A-C]\+$/{
  s/^\(.\+[[:space:]]\)\([0-9]\+\)[A-C]*$/\2 \1/
  h
  d
}
/^[[:space:]]*$/{ 
  g
  s/\n/ /g
  s/[[:space:]]\+/ /g
  p
  d
}
H
'



